[bastion]
<Public IP Address>

[masters]
<Private IP Address(es)>

[workers]
<Private IP Address(es)>

[workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i <path/to/private-key> -q root@<Bastion Public IP>" -i <path/to/private-key>'

[masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i <path/to/private-key> -q root@<Bastion Public IP>" -i <path/to/private-key>'
