- name: Create cni directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Download and setup cni plugins
  unarchive:
    src: "{{ cni_plugins_url }}/{{ cni_plugins_version }}/{{ cni_plugins_tarball }}"
    dest: "/opt/cni/bin"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  retries: 3
  delay: 5

- name: Download flannel manifest
  get_url:
    url: "https://raw.githubusercontent.com/flannel-io/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml"
    dest: /tmp/kube-flannel.yml
    mode: '0755'
  when: inventory_hostname in groups['masters']

- name: Set up Flannel CNI from manifest
  command: kubectl create -f /tmp/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: inventory_hostname in groups['masters']
