# The Nodeport Services displayed a failure while network packets cross the default
# network interface on ppc64le-https://jsw.ibm.com/browse/POWERCLOUD-16
# This workaround fixed above failure.
# Follow up task to remove this in future https://jsw.ibm.com/browse/POWERCLOUD-34
# 

- name: Enable and Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Stop and disable kubelet
  systemd:
    name: kubelet
    state: stopped
    enabled: no

- name: Reset kubeadm on all nodes
  become: yes
  ansible.builtin.shell: |
    pid=$(lsof -ti:10250) 
    if [ -n "$pid" ]; then 
      kill -9 $pid
    fi
    kubeadm reset -f
    systemctl stop kubelet
    systemctl disable kubelet
    rm -rf /etc/kubernetes/admin.conf /var/lib/kubelet /var/lib/etcd /etc/cni/net.d /var/lib/cni /root/.kube ~/.kube /etc/cni/net.d/*
    rm -rf /etc/kubernetes/admin.conf
    rm -rf /root/.kube/config
    rm -rf ~/.kube
    rm -rf /etc/cni/net.d/*
  
# - name: remove taint
#   command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane-; kubectl taint nodes --all node-role.kubernetes.io/master-"
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf
#   when: node_type == "master" and not ('workers' in groups and groups['workers'])

# - name: Get the kubeadm join command from the Kubernetes master.
#   command: kubeadm token create --print-join-command
#   changed_when: false
#   when: node_type == "master"
#   register: kubernetes_join_command_result

# - name: Set the kubeadm join command globally.
#   set_fact:
#     kubernetes_join_command: >
#       {{ kubernetes_join_command_result.stdout }}
#   when: kubernetes_join_command_result.stdout is defined
#   delegate_to: "{{ item }}"
#   delegate_facts: true
#   with_items: "{{ groups['all'] }}"

# - name: kubeadm join worker nodes
#   command: "{{ kubernetes_join_command }}"
#   when: node_type == "worker"
